nlp_engine_name: spacy
models:
  -
    lang_code: en
    model_name: en_core_web_lg
    
ner_model_configuration:
  labels_to_ignore:
  - O
  - PERSON
  - US_DRIVER_LICENSE
  - IN_PAN
  - DATE_TIME
  - LOCATION
  - ORGANIZATION
  aggregation_strategy: simple # "simple", "first", "average", "max"
  stride: 16
  alignment_mode: strict # "strict", "contract", "expand"

  