nlp_engine_name: spacy
models:
  -
    lang_code: fi
    model_name: fi_core_news_lg
    
ner_model_configuration:
  model_to_presidio_entity_mapping:
    PER: PERSON
    PERSON: PERSON
    LOC: LOCATION
    LOCATION: LOCATION
    GPE: LOCATION
    ORG: ORGANIZATION
    DATE: DATE_TIME
    TIME: DATE_TIME
    NORP: NRP
